site_name: RecoFinement
site_url: https://RomainCtl.github.io/RecoFinement/
repo_url: https://github.com/RomainCtl/RecoFinement
nav:
    - Home: index.md
    - Users:
        - Welcome: users/index.md
        - Getting started: users/gettingstarted.md
    - Developers:
        - Home: developers/index.md
        - Installation:
            - Preamble: developers/installation/index.md
            - With docker: developers/installation/withdocker.md
            - Without docker: developers/installation/withoutdocker.md
        - Data sources: developers/datasources.md
        - Architecture: developers/architecture.md
        - Application Services:
            - User Interface: developers/services/ui.md
            - API: developers/services/api.md
            - Recommendation Engine: developers/services/engine.md
            - Nginx: developers/services/nginx.md
        - External Services:
            - Mailjet: developers/external_services/mailjet.md
            - Spotify: developers/external_services/spotify.md
            - IMDB: developers/external_services/imdb.md
            - Google Books: developers/external_services/gbooks.md
        - Database: developers/database.md
    - Advise.ly:
        - About us: about.md

theme:
    name: material
    logo: assets/images/favicon.png
    favicon: assets/images/favicon.png
    custom_dir: docs/assets/overrides
    language: en
    font:
        text: Roboto
    features:
        - navigation.tabs
        - tabs
    palette:
        primary: black

extra_javascript:
    - assets/javascript/zoom_image.js
extra_css:
    - assets/stylesheet/extra.css

markdown_extensions:
    - codehilite
    - pymdownx.smartsymbols
    - admonition
    - pymdownx.superfences
    - pymdownx.tabbed

plugins:
    - search
