site_name: RecoFinement
site_url: https://RomainCtl.github.io/RecoFinement/
repo_url: https://github.com/RomainCtl/RecoFinement
nav:
    - Home: index.md
    - Users:
        - Home: users/index.md
        - Authentication:
            - Register: users/authentication/sign-up.md
            - Sign in: users/authentication/sign-in.md
        - Content visualisation:
            - Musics: users/content/musics.md
            - Movies: users/content/movies.md
            - Series: users/content/series.md
            - Games: users/content/games.md
            - Books: users/content/books.md
            - Applications: users/content/applications.md
            - Search content: users/content/search.md
        - Profile:
            - Manage your profile:
                - Edit your account: users/profile/edit-account.md
                - Manage your groups: users/profile/groups.md
                - Third-party applications: users/profile/tpapps.md
            - Your interests: users/profile/interests.md
        - Admin: users/admin/administration_panel.md
            - Sandbox: users/admin/sandbox.md
            - Media validation: users/admin/media_validation.md
    - Developers:
        - Home: developers/index.md
        - Installation: developers/installation.md
        - Data sources: developers/datasources.md
        - Architecture: developers/architecture.md
        - Application Services:
            - User Interface: developers/services/ui.md
            - API: developers/services/api.md
            - Recommendation Engine: developers/services/engine.md
            - Nginx: developers/services/nginx.md
        - External Services:
            - Mailjet: developers/external_services/mailjet.md
            - Spotify: developers/external_services/spotify.md
            - TMDB: developers/external_services/tmdb.md
            - Google Books: developers/external_services/gbooks.md
        - Database: developers/database.md
        - Event Sourcing: developers/event_sourcing.md 
        - SandBox: 
            - Profile: developers/sandbox/profile.md
            - Additional Content: developers/sandbox/additional_content.md
    - Advise.ly:
        - About us: about.md

theme:
    name: material
    logo: assets/images/favicon.png
    favicon: assets/images/favicon.png
    custom_dir: docs/assets/overrides
    language: en
    font:
        text: Roboto
    features:
        - navigation.tabs
        - tabs
    palette:
        primary: black

extra_javascript:
    - assets/javascript/zoom_image.js
extra_css:
    - assets/stylesheet/extra.css

markdown_extensions:
    - codehilite
    - pymdownx.smartsymbols
    - admonition
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed

plugins:
    - search
