site_name: RecoFinement
site_url: https://RomainCtl.github.io/RecoFinement/
repo_url: https://github.com/RomainCtl/RecoFinement
nav:
    - Home: index.md
    - Use RecoFinement:
        - Welcome: use/index.md
    - How to setup:
        - Getting started: setup/index.md
    - Advise.ly:
        - About us: about.md

theme:
    name: material
    custom_dir: docs/assets/overrides
    language: en
    font:
        text: Roboto
    features:
        - navigation.tabs
    palette:
        primary: black

extra_javascript:
    - assets/javascript/zoom_image.js
extra_css:
    - assets/stylesheet/extra.css

markdown_extensions:
    - codehilite
    - pymdownx.smartsymbols
    - admonition
    - pymdownx.superfences
    - pymdownx.tabbed

plugins:
    - search
